url: /
name: Crowded
permalink: /:title

markdown: kramdown
highlighter: rouge
permalink: pretty
plugins: plugins
paginate: 6

plugins: [jekyll-paginate, jekyll-feed]

team:
  - name: Josh Minnie
    aka: TruePico
    role: founder
    avatar: https://avatars.io/twitter/joshminnie
    bio: I live and breath the web. I love spending time with my family. If I'm not doing either of those, I'm probably sleeping. Owner of <a href="http://nissisolutions.com" target="_blank">Nissi Solutions</a>.
    social:
      twitter: TheTruePico
      github: joshminnie
      instagram: joshminnie
  - name: Josh Pennington
    aka: joshpennington
    role: admin
    avatar: https://pbs.twimg.com/profile_images/989535033596624896/lrL08dmY.jpg
    bio: PHP developer by day, geek at night. I watch too much Doctor Who.
    social:
      twitter: joshpennington
      github: joshpennington
      instagram: joshpennington/
      youtube: spartan8103
  - name: Keith Sayer
    aka: Vickriman
    role: admin
    avatar: https://avatars.io/twitter/vickriman
    social:
      twitter: vickriman
  - name: Corey Moag
    aka: Pack
    role: moderator
    avatar: https://avatars.io/twitter/cmoag322
    bio: Just your average nerdy goof. Working my way up the IT ladder.
    social:
      twitter: cmoag322
  - name: Jason Minnie
    aka: Firestarter
    role: moderator
    avatar: https://avatars.io/twitter/slick150_2000
    social:
      twitter: slick150_2000
