url: /
name: Crowded
permalink: /:title

markdown: kramdown
highlighter: rouge
permalink: pretty
plugins: plugins
paginate: 6

plugins: [jekyll-paginate, jekyll-feed]

team:
  - name: Joshua Minnie
    aka: TruePico
    gravatar: 0d9ad0a17b1f1e22d38997ecc8269596
    bio: I live and breath the web. I love spending time with my family. If I'm not doing either of those, I'm probably sleeping. Owner of <a href="http://nissisolutions.com" target="_blank">Nissi Solutions</a>.
    social:
      twitter: joshminnie
      github: joshminnie
      instagram: joshminnie
  - name: Josh Pennington
    aka: joshpennington
    gravatar: ac1c040c634e8690b4d4e2ffb8528d59
    bio: PHP developer by day, geek at night. I watch too much Doctor Who.
    social:
      twitter: joshpennington
      github: joshpennington
      instagram: joshpennington/
      youtube: spartan8103
